// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {nostr} from '../models';
import {main} from '../models';

export function DeleteEvent(arg1:string):Promise<void>;

export function DumpEvents():Promise<void>;

export function FollowContact(arg1:Array<string>):Promise<void>;

export function GenerateKeys():Promise<any>;

export function GetContactList(arg1:string):Promise<Array<string>>;

export function GetContactProfile(arg1:string):Promise<any>;

export function GetMetadataEvents(arg1:Array<string>):Promise<void>;

export function GetMyPubkey():Promise<string>;

export function GetRelays():Promise<Array<any>>;

export function GetTaggedEvents(arg1:string):Promise<Array<any>>;

export function GetTaggedProfiles(arg1:string):Promise<Array<any>>;

export function GetTextNotesByEventIds(arg1:Array<string>):Promise<Array<any>>;

export function GetTextNotesByPubkeys(arg1:Array<string>,arg2:string,arg3:boolean):Promise<void>;

export function GetTextNotesByPubkeysOptions(arg1:Array<string>,arg2:Array<number>,arg3:any,arg4:number,arg5:string,arg6:boolean):Promise<void>;

export function GetWritableRelays():Promise<Array<any>>;

export function LoginWithPin(arg1:string):Promise<void>;

export function Nip19Decode(arg1:string):Promise<string>;

export function PkToNpub(arg1:string):Promise<string>;

export function PostEvent(arg1:number,arg2:nostr.Tags,arg3:string):Promise<void>;

export function PublishContentToSelectedRelays(arg1:number,arg2:string,arg3:Array<any>,arg4:Array<string>):Promise<void>;

export function Quit():Promise<void>;

export function RefreshContactProfiles():Promise<void>;

export function RefreshFeed(arg1:string,arg2:boolean):Promise<void>;

export function RefreshFeedReset(arg1:string):Promise<void>;

export function SaveConfigDark(arg1:boolean):Promise<void>;

export function SaveNewKeys(arg1:{[key: string]: string}):Promise<void>;

export function SaveProfile(arg1:main.ProfileMetadata):Promise<void>;

export function SetLoginWithPrivKey(arg1:Array<string>):Promise<void>;

export function SetRelays(arg1:Array<any>):Promise<void>;

export function StartPolling():Promise<void>;

export function UnfollowContact(arg1:string):Promise<void>;
