// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteEvent(arg1) {
  return window['go']['main']['App']['DeleteEvent'](arg1);
}

export function DumpEvents() {
  return window['go']['main']['App']['DumpEvents']();
}

export function FollowContact(arg1) {
  return window['go']['main']['App']['FollowContact'](arg1);
}

export function GenerateKeys() {
  return window['go']['main']['App']['GenerateKeys']();
}

export function GetContactList(arg1) {
  return window['go']['main']['App']['GetContactList'](arg1);
}

export function GetContactProfile(arg1) {
  return window['go']['main']['App']['GetContactProfile'](arg1);
}

export function GetMetadataEvents(arg1) {
  return window['go']['main']['App']['GetMetadataEvents'](arg1);
}

export function GetMyPubkey() {
  return window['go']['main']['App']['GetMyPubkey']();
}

export function GetRelays() {
  return window['go']['main']['App']['GetRelays']();
}

export function GetTaggedEvents(arg1) {
  return window['go']['main']['App']['GetTaggedEvents'](arg1);
}

export function GetTaggedProfiles(arg1) {
  return window['go']['main']['App']['GetTaggedProfiles'](arg1);
}

export function GetTextNotesByEventIds(arg1) {
  return window['go']['main']['App']['GetTextNotesByEventIds'](arg1);
}

export function GetTextNotesByPubkeys(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTextNotesByPubkeys'](arg1, arg2, arg3);
}

export function GetTextNotesByPubkeysOptions(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['GetTextNotesByPubkeysOptions'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetWritableRelays() {
  return window['go']['main']['App']['GetWritableRelays']();
}

export function LoginWithPin(arg1) {
  return window['go']['main']['App']['LoginWithPin'](arg1);
}

export function Nip19Decode(arg1) {
  return window['go']['main']['App']['Nip19Decode'](arg1);
}

export function PkToNpub(arg1) {
  return window['go']['main']['App']['PkToNpub'](arg1);
}

export function PostEvent(arg1, arg2, arg3) {
  return window['go']['main']['App']['PostEvent'](arg1, arg2, arg3);
}

export function PublishContentToSelectedRelays(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PublishContentToSelectedRelays'](arg1, arg2, arg3, arg4);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RefreshContactProfiles() {
  return window['go']['main']['App']['RefreshContactProfiles']();
}

export function RefreshFeed(arg1, arg2) {
  return window['go']['main']['App']['RefreshFeed'](arg1, arg2);
}

export function RefreshFeedReset(arg1) {
  return window['go']['main']['App']['RefreshFeedReset'](arg1);
}

export function SaveConfigDark(arg1) {
  return window['go']['main']['App']['SaveConfigDark'](arg1);
}

export function SaveNewKeys(arg1) {
  return window['go']['main']['App']['SaveNewKeys'](arg1);
}

export function SetLoginWithPrivKey(arg1) {
  return window['go']['main']['App']['SetLoginWithPrivKey'](arg1);
}

export function SetRelays(arg1) {
  return window['go']['main']['App']['SetRelays'](arg1);
}

export function StartPolling() {
  return window['go']['main']['App']['StartPolling']();
}

export function UnfollowContact(arg1) {
  return window['go']['main']['App']['UnfollowContact'](arg1);
}
